# Generated by Django 5.0.9 on 2026-07-15 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome / Empresa')),
                ('cnpj', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=160)),
                ('telefone', models.CharField(blank=True, max_length=40)),
                ('municipio', models.CharField(blank=True, max_length=120, verbose_name='Município')),
                ('estado', models.CharField(blank=True, max_length=40)),
                ('pais', models.CharField(blank=True, max_length=60, verbose_name='País')),
                ('segmento', models.CharField(blank=True, max_length=120)),
                ('canal', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(blank=True, max_length=60)),
                ('produto_atual', models.CharField(blank=True, max_length=120)),
                ('consultor_atual', models.CharField(blank=True, max_length=120)),
                ('motivo_distrato', models.CharField(blank=True, max_length=160)),
                ('quem_fara_contato', models.CharField(blank=True, max_length=120, verbose_name='Quem fará o contato')),
                ('responsavel', models.CharField(blank=True, max_length=120)),
                ('data_onboarding', models.CharField(blank=True, max_length=40, verbose_name='Data de onboarding')),
                ('data_offboarding', models.CharField(blank=True, max_length=40, verbose_name='Data de offboarding')),
                ('qtd_socios', models.PositiveIntegerField(blank=True, null=True, verbose_name='Qtd. de sócios')),
                ('lt', models.CharField(blank=True, max_length=60, verbose_name='LT')),
                ('etapa', models.CharField(blank=True, choices=[('priorizado', 'Priorizado'), ('contato_realizado', 'Contato Realizado'), ('conectado', 'Conectado'), ('diagnostico', 'Diagnóstico'), ('proposta', 'Proposta'), ('reativado', 'Reativado'), ('perdido', 'Perdido')], db_index=True, help_text='Etapa atual no funil. Vazio = fora do funil (só na base).', max_length=30, null=True)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem dentro da coluna do Kanban.')),
                ('notas', models.TextField(blank=True, max_length=2000)),
                ('valor_contrato', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor do contrato recuperado (R$)')),
                ('meses_contrato', models.PositiveSmallIntegerField(blank=True, help_text='Parametriza a parcela mensal (valor ÷ meses). Vazio usa o padrão global.', null=True, verbose_name='Duração do contrato (meses)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ('ordem', 'nome'),
                'indexes': [models.Index(fields=['etapa'], name='crm_cliente_etapa_064831_idx'), models.Index(fields=['quem_fara_contato'], name='crm_cliente_quem_fa_118663_idx')],
            },
        ),
    ]
