# Generated by Django 5.0.9 on 2026-07-17 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('cor', models.CharField(default='#C7A444', help_text='Cor do selo do funil (hex, ex.: #3D7EC5).', max_length=9)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'funil',
                'verbose_name_plural': 'funis',
                'ordering': ('ordem', 'nome'),
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='funil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='crm.funil'),
        ),
    ]
