# Generated by Django 5.0.9 on 2026-07-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_seed_funis'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='faixa_faturamento',
            field=models.CharField(blank=True, max_length=60, verbose_name='Faixa de faturamento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='indicador_empresa',
            field=models.CharField(blank=True, max_length=160, verbose_name='Empresa do indicador'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='indicador_equipe',
            field=models.CharField(blank=True, max_length=120, verbose_name='Equipe do indicador'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='indicador_nome',
            field=models.CharField(blank=True, max_length=120, verbose_name='Indicado por'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='indicador_whatsapp',
            field=models.CharField(blank=True, max_length=40, verbose_name='WhatsApp do indicador'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='prioridade',
            field=models.CharField(blank=True, help_text='P1 a P5', max_length=10, verbose_name='Prioridade'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='qtd_indicacoes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Qtd. de indicações do indicador'),
        ),
    ]
