# Generated by Django 5.0.9 on 2026-07-27 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_cliente_faixa_faturamento_cliente_indicador_empresa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Para quem é a chave (ex.: 'n8n — sincronização diária').", max_length=80)),
                ('prefixo', models.CharField(db_index=True, editable=False, max_length=8, unique=True)),
                ('hash_chave', models.CharField(editable=False, max_length=64)),
                ('escopo', models.CharField(choices=[('leitura', 'Somente leitura'), ('escrita', 'Leitura e escrita')], default='leitura', max_length=10)),
                ('ativa', models.BooleanField(default=True, help_text='Desmarque para revogar imediatamente.')),
                ('expira_em', models.DateTimeField(blank=True, help_text='Opcional. Vazio = não expira.', null=True)),
                ('ultimo_uso_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys_criadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(help_text='Usuário em nome de quem a chave age — é ele que aparece em `criado_por` nos registros criados pela integração.', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'chave de API',
                'verbose_name_plural': 'chaves de API',
                'ordering': ('-criado_em',),
            },
        ),
    ]
