# Generated by Django 5.0.9 on 2026-08-03 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_cliente_etapa_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VinculoIdentidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identidade_id', models.UUIDField(db_index=True, unique=True, verbose_name='identidade no Conecta ID')),
                ('precisa_trocar_senha', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vinculo_identidade', to=settings.AUTH_USER_MODEL, verbose_name='usuário local')),
            ],
            options={
                'verbose_name': 'vínculo com o Conecta ID',
                'verbose_name_plural': 'vínculos com o Conecta ID',
            },
        ),
    ]
